global:
  scrape_interval: 5s
  scrape_timeout: 3s

scrape_configs:
  - job_name: 'scrapping-fastapi-app'

    metrics_path: /metrics
    scheme: http
    
    static_configs:
    - targets:
      - fastapi_app:8081