{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Нагрузка на сервис",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "Количество входящих запросов" },
    {
     "expr": "rate(http_requests_total{handler=\"/predict\"}[1m])",
     "legendFormat": " Частота входящих запросов "
    },
    {
     "expr": "rate(http_request_duration_seconds_count[5m])",
     "legendFormat": "К-во запросов в секунду"
    }
   ]
  },
  {
   "title": "Внутренние ошибки и их частота",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_error_counter_total", "legendFormat": "Общее к-во ошибок" },
    {
     "expr": "rate(app_error_counter_total_total{}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Распределение предсказания модели",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "delta(app_prediction_comparison_sum[5m]) / delta(app_prediction_comparison_count[5m])",
     "legendFormat": "Среднее"
    },
    {
     "expr": "histogram_quantile(0.5, delta(app_prediction_comparison_bucket[5m]))",
     "legendFormat": "Медианное значение"
    },
    {
     "expr": "histogram_quantile(0.05, delta(app_prediction_comparison_bucket[5m]))",
     "legendFormat": "5% Квантиль"
    },
    {
     "expr": "histogram_quantile(0.95, delta(app_prediction_comparison_bucket[5m]))",
     "legendFormat": "95% Квантиль"
    }
   ]
  },
  {
   "title": "Загрузка инфраструктуры",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "RAM" },
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "Process time per sec"
    }
   ]
  }
 ]
}